# ~/.config/kitty/kitty.conf

# Fuente y tamaño
font_family       Iosevka 
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 16.0


# No parpadeo del cursor
cursor_blink_interval 0

# Personalización del cursor
cursor_shape beam
cursor_beam_thickness 1.5

# Transparencia de fondo (0 a 1)
background_opacity 0.85

# Padding
window_padding_width 0
# Número de líneas de historial a mantener
scrollback_lines 10000

# URLs
url_style curly
open_url_with default
detect_urls yes

# Copiar al portapapeles al seleccionar texto
copy_on_select yes

# Pestañas estilizadas
tab_bar_style powerline
tab_powerline_style angled
active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold
inactive_tab_foreground #444
inactive_tab_background #999

# Themes
include ~/.config/kitty/Tokyo Night.conf
#include ~/.config/kitty/GitHub Dark.conf


# Atajos de teclado útiles
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down
map ctrl+shift+enter new_window
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+l next_layout

# Habilitar ligaduras de fuente
disable_ligatures never

# Sonido de campana
enable_audio_bell no
visual_bell_duration 0.1

# Abrir enlaces con un clic
mouse_map left click ungrabbed mouse_handle_click selection link prompt

# Confirmar cierre
confirm_os_window_close 0

# # BEGIN_KITTY_FONTS
# font_family      family="IBm"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# # END_KITTY_FONTS
