# PRESET: FiraCode — clásica, ligaduras
font_family        family="FiraCode Nerd Font Mono" style="Regular" features="+calt +liga"
bold_font          family="FiraCode Nerd Font Mono" style="Bold" features="+calt +liga"
italic_font        auto
bold_italic_font   auto
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%