# PRESET: GeistMono — moderna, limpia
font_family        family="GeistMono Nerd Font Mono" style="Regular"
bold_font          family="GeistMono Nerd Font Mono" style="Bold"
italic_font        auto
bold_italic_font   auto
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 1
modify_font underline_position  2
modify_font underline_thickness 70%