# PRESET: Maple Mono NF — redonda, ligaduras (calt+liga) + cursiva caligráfica en italics
font_family        family="Maple Mono NF" style="Regular" features="+calt +liga"
bold_font          family="Maple Mono NF" style="Bold" features="+calt +liga"
italic_font        family="Maple Mono NF" style="Italic" features="+calt +liga"
bold_italic_font   family="Maple Mono NF" style="Bold Italic" features="+calt +liga"
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 1
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures never
