# PRESET: MesloLGS — Default de powerlevel10k/oh-my-zsh
font_family        family="MesloLGS Nerd Font Mono"
bold_font          off
italic_font        auto
bold_italic_font   auto
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures always
