# PRESET: Monaspace (GitHub) — Neon recto + Radon MANUSCRITA en cursivas
# texture-healing + todas las ligaduras (ss01-ss10). Así lo muestran en los dotfiles.
font_family        family="MonaspiceNe Nerd Font Mono" style="Regular" features="+calt +liga +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10"
bold_font          family="MonaspiceNe Nerd Font Mono" style="Bold" features="+calt +liga +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10"
italic_font        family="MonaspiceRn Nerd Font Mono" style="Italic" features="+calt +liga +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10"
bold_italic_font   family="MonaspiceRn Nerd Font Mono" style="Bold Italic" features="+calt +liga +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10"
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures never
