# PRESET: SauceCodePro — Source Code Pro Light 15 — visible y clara
font_family        family="SauceCodePro Nerd Font Mono" style="Light"
bold_font          family="SauceCodePro Nerd Font Mono" style="Medium"
italic_font        family="SauceCodePro Nerd Font Mono" style="Light Italic"
bold_italic_font   family="SauceCodePro Nerd Font Mono" style="Medium Italic"
font_size 15
modify_font cell_width  92%
modify_font cell_height  96%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures always
