# PRESET: SpaceMono — Space Mono (Google) — con carácter
font_family        family="SpaceMono Nerd Font Mono"
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures always
