# PRESET: Victor Mono — cursiva caligráfica REAL en italics (su sello) + ligaduras
font_family        family="VictorMono Nerd Font Mono" style="Regular" features="+calt +liga"
bold_font          family="VictorMono Nerd Font Mono" style="Bold" features="+calt +liga"
italic_font        family="VictorMono Nerd Font Mono" style="Italic" features="+calt +liga"
bold_italic_font   family="VictorMono Nerd Font Mono" style="Bold Italic" features="+calt +liga"
font_size 13
modify_font cell_width  100%
modify_font cell_height 100%
modify_font baseline 0
modify_font underline_position  2
modify_font underline_thickness 70%
disable_ligatures never
